[workspace]
members = [
    "platforms/config",
    "apps/factorio",
    "apps/factorio/native",
    "apps/factorio/wasm",
    "apps/factorio/properties",
    "crates/transport",
    "platforms/local",
    "platforms/document",
    "platforms/transport",
    "apps/factorio/cli",
    "platforms/oauth",
    "platforms/model",
    "crates/http",
    "platforms/sqlite",
    "apps/testy",
    "apps/testy/local",
    "apps/testy/wasm",
    "apps/testy/properties",
    "crates/store",
    "crates/access",
    "crates/document",
    "crates/oidc",
    "apps/authy",
    "apps/authy/native",
    "apps/authy/wasm",
    "apps/chatty",
    "apps/chatty/native",
    "apps/chatty/wasm",
    "crates/identity",
    "platforms/crypto",
    "tests/properties",
    "tests/browser",
    "tools/cli",
]
resolver = "3"
default-members = [
    "platforms/config",
    "apps/factorio",
    "apps/factorio/native",
    "apps/factorio/wasm",
    "crates/http",
    "platforms/oauth",
    "platforms/model",
    "apps/chatty",
    "apps/chatty/native",
    "apps/chatty/wasm",
    "crates/oidc",
    "platforms/document",
    "platforms/transport",
    "apps/factorio/cli",
    "apps/authy",
    "apps/authy/native",
    "apps/authy/wasm",
    "crates/document",
    "crates/access",
    "crates/identity",
    "platforms/crypto",
    "crates/store",
    "platforms/sqlite",
    "crates/transport",
    "platforms/local",
    "apps/testy",
    "apps/testy/local",
]

[workspace.package]
version = "0.0.0"
edition = "2024"
publish = false

[workspace.dependencies]
snap-config = { path = "platforms/config" }
snap-http = { path = "crates/http" }
snap-model-local = { path = "platforms/model" }
chatty = { path = "apps/chatty" }
snap-access = { path = "crates/access" }
snap-document = { path = "crates/document" }
snap-identity = { path = "crates/identity" }
snap-oidc = { path = "crates/oidc" }
authy = { path = "apps/authy" }
snap-store = { path = "crates/store" }
wasm-bindgen = "=0.2.128"
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }

[workspace.lints.rust]
unsafe_code = "forbid"
