[workspace]
members = [
    "crates/protocol",
    "crates/runtime",
    "crates/client",
    "bindings/wasm",
    "platforms/native",
    "platforms/browser",
    "apps/healthy",
    "apps/healthy/native",
    "apps/healthy/wasm",
    "tools/cli",
]
resolver = "3"

[workspace.package]
version = "0.0.0"
edition = "2024"
publish = false

[workspace.dependencies]
snap-protocol = { path = "crates/protocol" }
snap-runtime = { path = "crates/runtime" }
snap-client = { path = "crates/client" }
snap-browser = { path = "platforms/browser" }
snap-native = { path = "platforms/native" }
snap-client-wasm = { path = "bindings/wasm" }
wasm-bindgen = "=0.2.128"
healthy = { path = "apps/healthy" }
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }

[workspace.lints.rust]
unsafe_code = "forbid"
