[workspace]
members = [
    "crates/execution",
    "crates/transport",
    "platforms/local",
    "apps/testy",
    "apps/testy/local",
    "crates/protocol",
    "crates/http",
    "crates/oidc",
    "crates/llm",
    "apps/chatty",
    "apps/chatty/native",
    "apps/chatty/workers",
    "crates/identity",
    "crates/store",
    "crates/runtime",
    "crates/client",
    "bindings/wasm",
    "platforms/native",
    "platforms/memory",
    "platforms/browser",
    "platforms/web",
    "platforms/workers",
    "apps/healthy/workers",
    "tests/workers",
    "apps/healthy",
    "apps/healthy/native",
    "apps/healthy/wasm",
    "apps/authy",
    "apps/authy/native",
    "apps/authy/wasm",
    "apps/authy/workers",
    "tools/cli",
]
resolver = "3"
default-members = [
    "crates/execution",
    "crates/transport",
    "platforms/local",
    "apps/testy",
    "apps/testy/local",
]

[workspace.package]
version = "0.0.0"
edition = "2024"
publish = false

[workspace.dependencies]
snap-http = { path = "crates/http" }
snap-oidc = { path = "crates/oidc" }
snap-llm = { path = "crates/llm" }
chatty = { path = "apps/chatty" }
snap-protocol = { path = "crates/protocol" }
snap-identity = { path = "crates/identity" }
snap-store = { path = "crates/store" }
snap-runtime = { path = "crates/runtime" }
snap-client = { path = "crates/client" }
snap-browser = { path = "platforms/browser" }
snap-web = { path = "platforms/web" }
snap-workers = { path = "platforms/workers" }
worker = "=0.8.6"
snap-native = { path = "platforms/native" }
snap-memory = { path = "platforms/memory" }
snap-client-wasm = { path = "bindings/wasm" }
wasm-bindgen = "=0.2.128"
healthy = { path = "apps/healthy" }
authy = { path = "apps/authy" }
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }

[workspace.lints.rust]
unsafe_code = "forbid"
