import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { Factorio, subscribe, type Workspace, type Ticket } from "../client";
import "./style.css";
const client = new Factorio(location.origin);
const empty: Ticket = { id: "", title: "", description: "", modules: [], status: "draft", notes: "", parent: null, blockers: [] };
function App() {
  const [workspace, setWorkspace] = useState<Workspace | null>(null), [identified, setIdentified] = useState(false), [error, setError] = useState(""), [ticket, setTicket] = useState<Ticket>(empty), [token, setToken] = useState(""), [busy, setBusy] = useState(false);
  useEffect(() => { let close: (() => void) | undefined, disposed = false; void client.identify().then(async identity => { if (disposed) return; setIdentified(identity.identified); if (identity.identified) { const stop = await subscribe(client, (w,e) => { if (!disposed) { setWorkspace(w); setError(e ?? ""); } }); if (disposed) stop(); else close = stop; } }).catch(e=>setError(String(e))); return () => { disposed = true; close?.(); }; }, []);
  async function run(action: () => Promise<unknown>) { setBusy(true); setError(""); try { await action(); } catch(e) { setError(String(e)); } finally { setBusy(false); } }
  return <main><header><h1>Factorio</h1><p>Local tickets, isolated work and human acceptance.</p>{identified ? <><button disabled={busy} onClick={()=>void run(async()=>setToken((await client.agentToken()).token))}>Create agent token</button> <button onClick={()=>void run(async()=>location.assign((await client.logout()).redirect))}>Sign out</button></> : <a href="/auth/login">Continue with Authy</a>}</header>
    {error && <p role="alert">{error}</p>}{token && <label>Agent token. Copy once, then dismiss.<input aria-label="Agent token" type="password" readOnly value={token}/><button onClick={()=>setToken("")}>Dismiss token</button></label>}
    {workspace && <><p>{workspace.config.repository} · {workspace.config.mainline}</p><section><h2>Tickets</h2><div className="columns"><div>{Object.values(workspace.tickets).map(t=><article id={`ticket-${t.id}`} key={t.id}><h3>{t.id}: {t.title}</h3><p>{t.status} · {t.modules.join(", ")}</p><p>{t.description}</p><p>Blockers: {t.blockers.map(id=><a key={id} href={`#ticket-${id}`}>{id} ({workspace.tickets[id]?.status}) </a>)}</p>{t.parent && <a href={`#ticket-${t.parent}`}>Parent {t.parent}</a>}<p>{t.notes}</p><button onClick={()=>setTicket(t)}>Edit</button> <button disabled={busy} onClick={()=>void run(()=>client.command({ command:"delete_ticket",id:t.id }))}>Delete</button></article>)}</div><form onSubmit={e=>{e.preventDefault();void run(async()=>{await client.command({command:"ticket",ticket});setTicket(empty);});}}><h3>Edit ticket</h3>{(["id","title","description","notes"] as const).map(field=><label key={field}>{field}<textarea aria-label={field} required={field==="id"||field==="title"} value={ticket[field]} onChange={e=>setTicket({...ticket,[field]:e.target.value})}/></label>)}<label>Modules<input aria-label="Modules" value={ticket.modules.join(",")} onChange={e=>setTicket({...ticket,modules:e.target.value.split(",").filter(Boolean)})}/></label><p>Available: {Object.keys(workspace.config.modules).join(", ")}, *</p><label>Blockers<input aria-label="Blockers" value={ticket.blockers.join(",")} onChange={e=>setTicket({...ticket,blockers:e.target.value.split(",").filter(Boolean)})}/></label><label>Parent<input value={ticket.parent??""} onChange={e=>setTicket({...ticket,parent:e.target.value||null})}/></label><label>Status<select value={ticket.status} onChange={e=>setTicket({...ticket,status:e.target.value as Ticket["status"]})}><option>draft</option><option>ready</option><option>cancelled</option>{ticket.status==="done"&&<option>done</option>}</select></label><button disabled={busy}>Save ticket</button> <button type="button" onClick={()=>setTicket(empty)}>New ticket</button></form></div></section>
    <section><h2>Sessions</h2><p>Start and publish through <code>bin/factory</code>. Inspect and approve the exact candidate here.</p>{Object.values(workspace.sessions).map(s=><article key={s.id}><h3>{s.id} · {s.phase}</h3><p>{s.prompt}</p><p>Claims: {s.modules.join(", ")} · Tickets: {s.tickets.join(", ")}</p><p>Worktree: <code>{s.worktree}</code><br/>Data: <code>{s.data}</code> · Port: {s.port}</p><p>OpenCode: <code>opencode --session {s.conversation}</code></p>{s.error&&<p role="alert">{s.error}</p>}{s.candidate&&<><p>Candidate: <code>{s.candidate.commit}</code><br/>Mainline at publication: <code>{s.candidate.target}</code></p><pre>{s.candidate.evidence}</pre>{s.candidate.findings.map((f,i)=><p key={i}>{f.text}: {f.disposition||"Unresolved"}</p>)}{s.candidate.approval?<p>Approved by {s.candidate.approval.human} for {s.candidate.approval.commit}</p>:s.phase==="published"&&<button disabled={busy} onClick={()=>{if(window.confirm(`I have reviewed and approve candidate ${s.candidate!.commit} for local integration.`))void run(()=>client.approve(s.id,s.candidate!.commit));}}>Approve candidate as human</button>}</>}{s.integration&&<p>Integrated commit: <code>{s.integration}</code></p>}<div>{["accept","recover","cleanup","abandon"].map(command=><button key={command} disabled={busy} onClick={()=>{if(command!=="abandon"||window.confirm("Abandon this attempt and release its claims? Unmerged work will be preserved."))void run(()=>client.command({command,id:s.id}));}}>{command}</button>)}</div></article>)}</section></>}
  </main>;
}
createRoot(document.getElementById("root")!).render(<App/>);
