import { test, expect, type Page } from "@playwright/test";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { writeFile, readFile } from "node:fs/promises";
import { resolve } from "node:path";
const exec = promisify(execFile);
const base=process.env.FACTORIO_TEST_URL!, dir=process.env.FACTORIO_FIXTURE_DIR!, root=resolve(import.meta.dirname,"../../../..");
async function invoke(page:Page,operation:string,input:unknown,bearer="") {
  return page.evaluate(({operation,input,bearer})=>new Promise<any>((resolve,reject)=>{
    const socket=new WebSocket(`${location.origin.replace(/^http/,"ws")}/transport`);
    let accepted=false;
    const timer=setTimeout(()=>{socket.close();reject(new Error("WS timeout"));},10000);
    socket.onopen=()=>socket.send(JSON.stringify({Connect:{bearer,client_id:`fixture-${Math.random()}`}}));
    socket.onmessage=event=>{
      const frame=JSON.parse(String(event.data));
      if(frame.Attached) socket.send(JSON.stringify({Invoke:{id:1,operation,input}}));
      if(frame.Failed){clearTimeout(timer);socket.close();reject(new Error(JSON.stringify(frame.Failed)));}
      for(const event of frame.Events??[]) {
        if(event.Accepted) accepted=true;
        if(event.Completed){clearTimeout(timer);socket.close();resolve({accepted,...event.Completed.outcome});}
      }
    };
  }),{operation,input,bearer});
}
test("fixture-only human acceptance, CLI/UI records, exclusions and restart recovery",async({page,browser})=>{
  await page.setViewportSize({width:390,height:844});
  // HTTP tailnet origins lack randomUUID, including in mobile Safari.
  await page.addInitScript(()=>Reflect.deleteProperty(Object.getPrototypeOf(crypto),"randomUUID"));
  const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
  page.on("console",message=>{if(message.type()==="error" && /removeChild|already been passed to createRoot/.test(message.text()))errors.push(message.text());});
  await page.goto(base);await page.getByRole("link",{name:"Continue with Authy"}).click();
  await page.getByRole("button",{name:"New here? Create account",exact:true}).click();
  await page.getByLabel("Email",{exact:true}).fill(`factorio-${Date.now()}@example.test`);await page.getByLabel("Password",{exact:true}).fill("Factorio fixture password");
  await page.getByRole("button",{name:"Create account",exact:true}).click();await page.getByRole("button",{name:"Allow",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Create your first workspace",exact:true})).toBeVisible();
  await page.getByRole("button",{name:"Create workspace",exact:true}).click();
  await page.getByRole("navigation",{name:"Workspace"}).getByRole("link",{name:"Tickets",exact:true}).click();
  await expect(page.getByText("No tickets yet",{exact:true})).toBeVisible();
  await page.getByRole("navigation",{name:"Workspace"}).getByRole("link",{name:"Intakes",exact:true}).click();
  const identity=await(await page.request.get(`${base}/api/session`)).json();
  const mutationHeaders={origin:base,"x-snap-csrf":identity.csrf};
  const workspace=(await invoke(page,"factorio.workspaces",{})).Ok[0].id;
  for(let n=0;n<6;n++) expect((await invoke(page,"factorio.command",{workspace,command:{command:"ticket",ticket:{id:`preceding-${n}`,title:`Earlier ticket ${n}`,description:"Existing work",modules:["a"],status:"draft",notes:"",parent:null,blockers:[]}}})).Ok).toBeNull();
  await page.getByLabel("Your idea",{exact:true}).fill("Improve navigation on my phone");
  await page.getByRole("button",{name:"Work through this",exact:true}).click();
  await expect(page.getByText("Which navigation outcome matters most?",{exact:true})).toBeVisible();
  await expect(page.getByLabel("OpenCode model",{exact:true})).toHaveText("opencode-go/muse-spark-1.3-contributor");
  await expect(page.getByRole("heading",{name:"Tickets",exact:true})).toHaveCount(0);
  for (const height of [844, 420, 844]) {
    await page.setViewportSize({width:390,height});
    await expect.poll(async()=>page.locator(".thread-bottom").evaluate(e=>Math.abs(e.getBoundingClientRect().bottom-document.querySelector(".mobile-navigation")!.getBoundingClientRect().top)<2)).toBe(true);
    await page.locator(".thread-scroll").evaluate(e=>e.scrollTop=0);
    await expect(page.getByRole("button",{name:"Send reply",exact:true})).toBeVisible();
  }
  await page.getByRole("button",{name:"Allow once",exact:true}).click();
  await expect(page.getByLabel("Desired outcome",{exact:true})).toBeVisible();
  await expect(page.getByLabel("Alternate outcome",{exact:true})).toHaveCount(0);
  await expect(page.getByLabel("Unanswered follow-up",{exact:true})).toHaveCount(0);
  await page.getByLabel("Scope custom choices",{exact:true}).fill("");
  const scope=page.getByRole("listbox",{name:"Scope",exact:true});
  await scope.selectOption("known");
  await expect(page.getByLabel("Desired outcome",{exact:true})).toHaveCount(0);
  await expect(page.getByLabel("Alternate outcome",{exact:true})).toBeVisible();
  await scope.selectOption([]);
  await page.getByRole("button",{name:"Send answers",exact:true}).click();
  await expect(scope).toBeVisible();
  expect(await scope.evaluate((e:HTMLSelectElement)=>e.validity.valueMissing)).toBe(true);
  await page.getByLabel("Scope custom choices",{exact:true}).fill("other, other");
  await scope.selectOption("known");
  await scope.selectOption([]);
  await expect(page.getByLabel("Alternate outcome",{exact:true})).toHaveCount(0);
  await page.getByLabel("Desired outcome",{exact:true}).fill("Keep ticket links visible on my phone");
  await page.getByRole("button",{name:"Send answers",exact:true}).click();
  const draft=page.locator("article").filter({has:page.getByRole("heading",{name:"Improve mobile navigation",exact:true})});
  const initialConversationURL = page.url();
  await expect(page.locator(".draft-summary").getByRole("link",{name:"Improve mobile navigation",exact:true})).toBeVisible();
  await page.locator(".draft-summary").getByRole("link",{name:"Improve mobile navigation",exact:true}).click();
  await expect.poll(()=>draft.evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.top<innerHeight;})).toBe(true);
  const draftURL = page.url();
  await page.getByRole("button",{name:/Open tickets/}).click();
  const drawer = page.getByRole("dialog", {name:"Open tickets",exact:true});
  await expect(drawer).toBeVisible();
  await expect(drawer.getByRole("link").first()).toContainText("Improve mobile navigation");
  await drawer.getByRole("link",{name:/Earlier ticket 0/}).click();
  await expect(drawer).not.toBeVisible();
  await expect(page.getByRole("heading",{name:"Earlier ticket 0",exact:true})).toBeVisible();
  await page.getByRole("navigation",{name:"Workspace"}).getByRole("link",{name:"Intakes",exact:true}).click();
  await expect(page.getByLabel("Reply",{exact:true})).toBeVisible();
  await page.getByRole("navigation",{name:"Workspace"}).getByRole("link",{name:"Tickets",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Earlier ticket 0",exact:true})).toBeVisible();
  await page.getByRole("button",{name:/Open tickets/}).click();
  await page.keyboard.press("Escape");
  await expect(drawer).not.toBeVisible();
  await expect(page.getByRole("button",{name:/Open tickets/})).toBeFocused();
  await page.goto(draftURL);
  await expect(draft).toBeVisible();
  await page.reload();
  await expect(draft).toBeVisible();
  await page.goto(new URL(draftURL).origin + "/#ticket-" + decodeURIComponent(new URL(draftURL).pathname.split("/").at(-1)!));
  await expect(page).toHaveURL(draftURL);
  await page.goto(initialConversationURL);
  await page.getByLabel("Reply",{exact:true}).fill("That is the right scope.");
  await page.getByRole("button",{name:"Send reply",exact:true}).click();
  await expect(page.getByText("Your additional context is recorded.")).toBeVisible();
  const conversationURL=page.url();
  const intakeID=decodeURIComponent(new URL(conversationURL).pathname.split("/").at(-1)!);
  const state=(await invoke(page,"factorio.workspace",{workspace})).Ok;
  const sessionPath=`/api/session/${state.intakes[intakeID].conversation}`;
  await page.request.post(`${process.env.FACTORIO_FIXTURE_URL}/opencode/request`,{data:{method:"POST",path:`${sessionPath}/model`,body:{model:{providerID:"openai",id:"expensive-fixture"}}}});
  await expect(page.getByLabel("OpenCode model",{exact:true})).toHaveText("openai/expensive-fixture");
  await page.getByText("Drafts and session details",{exact:false}).click();
  await page.getByRole("button",{name:"Reconnect session",exact:true}).click();
  await expect(page.getByLabel("OpenCode model",{exact:true})).toHaveText("opencode-go/muse-spark-1.3-contributor");
  await page.getByText("Drafts and session details",{exact:false}).click();
  const stranger=await browser.newContext();
  try {
    const other=await stranger.newPage();await other.goto(base);await other.getByRole("link",{name:"Continue with Authy"}).click();await other.getByRole("button",{name:"New here? Create account",exact:true}).click();await other.getByLabel("Email",{exact:true}).fill(`other-${Date.now()}@example.test`);await other.getByLabel("Password",{exact:true}).fill("Other fixture password");await other.getByRole("button",{name:"Create account",exact:true}).click();await other.getByRole("button",{name:"Allow",exact:true}).click();await expect(other.getByRole("heading",{name:"Create your first workspace",exact:true})).toBeVisible();
    expect((await invoke(other,"factorio.workspaces",{})).Ok).toEqual([]);
    const forbidden=await invoke(other,"factorio.workspace",{workspace});expect(forbidden.accepted).toBe(false);expect(forbidden.Err).toBeDefined();
    expect((await other.request.get(`${base}/api/workspaces/${workspace}/intakes/${intakeID}/events`)).ok()).toBe(false);
    const identity=await(await other.request.get(`${base}/api/session`)).json();
    expect((await other.request.post(`${base}/api/workspaces/${workspace}/intakes/${intakeID}/opencode`,{headers:{origin:base,"x-snap-csrf":identity.csrf},data:{action:"interrupt"}})).ok()).toBe(false);
  } finally {await stranger.close();}
  await page.reload();
  await expect(page.getByText("Your additional context is recorded.")).toBeVisible();
  expect(page.url()).toBe(conversationURL);
  await page.getByRole("button",{name:"Mark implementation tickets ready",exact:true}).click();
  await expect(page.locator(".draft-summary").getByText("ready",{exact:true})).toBeVisible();
  await page.screenshot({path:"/tmp/opencode/factorio-thread-ui.png"});
  await page.setViewportSize({width:1280,height:900});
  await expect(page.getByLabel("OpenCode model",{exact:true})).toBeVisible();
  await page.screenshot({path:"/tmp/opencode/factorio-thread-desktop-ui.png"});
  await page.setViewportSize({width:390,height:844});
  await page.getByRole("link",{name:"Back to intakes"}).click();
  await expect(page.getByLabel("Your idea",{exact:true})).toBeVisible();
  await page.goBack();
  await expect(page.getByLabel("Reply",{exact:true})).toBeVisible();
  await page.goForward();
  await page.goto(draftURL);
  await expect(draft.getByText("ready",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:/Open tickets/}).click();
  await page.screenshot({path:"/tmp/opencode/factorio-drawer-ui.png"});
  await page.getByRole("button",{name:"Close work list"}).click();
  await page.screenshot({path:"/tmp/opencode/factorio-mobile-ui.png"});
  await page.setViewportSize({width:1440,height:900});
  await expect(page.getByRole("navigation",{name:"Ticket list"})).toBeVisible();
  await page.screenshot({path:"/tmp/opencode/factorio-desktop-ui.png"});
  await page.setViewportSize({width:390,height:844});
  await draft.getByRole("button",{name:"Edit ticket",exact:true}).click();
  await expect(page.getByLabel("description",{exact:true})).toHaveValue(/Acceptance:/);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await draft.getByText("More ticket actions",{exact:true}).click();
  page.once("dialog",d=>d.accept());
  await draft.getByRole("button",{name:"Delete",exact:true}).click();
  await expect(draft).toHaveCount(0);
  await page.getByLabel("Account",{exact:true}).click();
  await page.getByRole("button",{name:"Create agent token",exact:true}).click();const token=await page.getByLabel("Agent token",{exact:true}).inputValue();expect(token.length).toBeGreaterThan(32);await page.getByRole("button",{name:"Dismiss token"}).click();
  await page.getByLabel("Account",{exact:true}).click();
  async function cli(args:string[]){const {stdout}=await exec("bun",[`${root}/apps/factorio/cli.ts`,...args],{cwd:root,timeout:15000,env:{...process.env,FACTORIO_OPENCODE:`${dir}/bin/opencode`,FACTORIO_ORIGIN:base,FACTORIO_TOKEN:token}});return JSON.parse(stdout);}
  const intake=(Object.values((await cli(["status"])).intakes) as {id:string;conversation:string}[])[0]!;
  expect((await cli(["intake","--resume",intake.id])).resumed).toBe(intake.conversation);
  const readIntake=()=>invoke(page,"factorio.intake-read",{workspace,id:intake.id},token);
  expect((await readIntake()).Ok.intake.id).toBe(intake.id);
  await page.goto(`${base}/intakes`);await page.getByRole("navigation",{name:"Conversations"}).getByRole("link").click();
  await page.getByText("Drafts and session details",{exact:true}).click();
  page.once("dialog",d=>d.accept());
  await page.getByRole("button",{name:"Delete conversation",exact:true}).click();
  await expect(page.getByLabel("Your idea",{exact:true})).toBeVisible();
  expect((await cli(["status"])).intakes[intake.id]).toBeUndefined();
  expect((await readIntake()).Err).toBeDefined();
  const replacement=await invoke(page,"factorio.intake-create",{workspace,id:intake.id,description:"Replacement intake"});
  expect(replacement.Ok.id).toBe(intake.id);expect(replacement.Ok.conversation).not.toBe(intake.conversation);
  expect((await invoke(page,"factorio.intake-delete",{workspace,id:intake.id})).Ok).toBeNull();
  expect((await page.request.post(`${base}/api/command`,{headers:mutationHeaders,data:{command:"delete_ticket",id:"preceding-0"}})).ok()).toBe(false);
  const ticket=(id:string,blockers:string[]=[])=>({id,title:id,description:"Fixture implementation",modules:["a"],status:"ready",notes:"",parent:null,blockers});
  for(const t of [ticket("first"),ticket("dependent",["first"])]){const file=`${dir}/${t.id}.json`;await writeFile(file,JSON.stringify(t));await cli(["ticket",file]);}
  await page.goto(`${base}/tickets/first`);await expect(page.locator("#ticket-first").getByRole("heading",{name:"first",exact:true})).toBeVisible();
  await page.goto(`${base}/tickets/dependent`);await expect(page.getByRole("link",{name:"first (ready)"})).toBeVisible();
  await expect(cli(["start","--id","blocked","--tickets","dependent","--modules","a","--","blocked"])).rejects.toThrow();
  const a=(await cli(["start","--id","one","--tickets","first","--modules","a","--","first change"])).session;
  const b=(await cli(["start","--id","two","--modules","b","--","parallel change"])).session;
  expect(a.port).not.toBe(b.port);expect(a.data).not.toBe(b.data);
  await expect(cli(["start","--id","overlap","--modules","a,b","--","overlap"])).rejects.toThrow();
  await expect(cli(["start","--id","whole","--modules","*","--","whole"])).rejects.toThrow();
  const conversations=JSON.parse(await readFile(`${dir}/conversations.json`,"utf8"));expect(conversations[a.conversation].directory).toBe(a.worktree);
  await writeFile(`${a.worktree}/crates/a/file`,"implemented");await exec("git",["add","."],{cwd:a.worktree});await exec("git",["-c","user.name=Fixture","-c","user.email=fixture@localhost","commit","-m","fixture implementation"],{cwd:a.worktree});
  await writeFile(`${dir}/evidence.txt`,"Fixture checks passed; test review found no unresolved findings.");
  const published=await cli(["publish","one","--evidence",`${dir}/evidence.txt`]);const candidate=published.sessions.one.candidate.commit;
  await expect(cli(["accept","one"])).rejects.toThrow();
  const denied=await invoke(page,"factorio.command",{workspace,command:{command:"approve",id:"one",commit:candidate}},token);expect(denied.accepted).toBe(false);expect(denied.Err).toBeDefined();
  // This automated account approves disposable fixture code, never user work.
  await page.goto(`${base}/sessions/one`);
  page.once("dialog",d=>d.accept());await page.getByRole("button",{name:"Approve candidate as human"}).click();
  await expect.poll(async()=>Boolean((await cli(["status"])).sessions.one.candidate.approval)).toBe(true);
  await cli(["accept","one"]);expect(await readFile(`${dir}/repo/crates/a/file`,"utf8")).toBe("implemented");
  await expect(page.locator("article").filter({has:page.getByRole("heading",{name:"one",exact:true})}).getByText("complete",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:/Open sessions/}).click();
  await expect(page.getByRole("dialog").getByRole("navigation",{name:"Session list"}).getByRole("link",{name:/^one /})).toHaveCount(0);
  await page.getByRole("dialog").getByRole("combobox",{name:"Show sessions",exact:true}).selectOption("all");
  await expect(page.getByRole("dialog").getByRole("navigation",{name:"Session list"}).getByRole("link",{name:/^one /})).toBeVisible();
  await page.getByRole("button",{name:"Close work list"}).click();
  await page.goto(`${base}/tickets/dependent`);
  await expect(page.getByRole("link",{name:"first (done)"})).toBeVisible();
  const dependent=(await cli(["start","--id","next","--tickets","dependent","--modules","a","--","dependent now ready"])).session;expect(dependent.phase).toBe("active");
  await cli(["abandon","two"]);await expect(cli(["start","--id","fail","--modules","b","--","failed setup"])).rejects.toThrow(/fixture setup failure/);
  await fetch(`${process.env.FACTORIO_FIXTURE_URL}/restart`);await expect(cli(["start","--id","collision","--modules","b","--","collision"])).rejects.toThrow();
  const failed=(await cli(["status"])).sessions.fail;expect(failed.phase).toBe("starting");await writeFile(`${failed.data}/permit`,"retry fixture hook");
  await cli(["recover","fail"]);expect((await cli(["status"])).sessions.fail.phase).toBe("active");
  await page.goto(`${base}/sessions/fail`);await page.reload();const failedCard=page.locator("article").filter({has:page.getByRole("heading",{name:"fail",exact:true})});await expect(failedCard.getByText("active",{exact:true})).toBeVisible();
  if(process.env.FACTORIO_TEST_DEV){
    const css=`${root}/apps/factorio/web/style.css`;await writeFile(css,await readFile(css,"utf8")+"\nbody { --factorio-probe: active; }\n");
    await expect.poll(()=>page.evaluate(()=>getComputedStyle(document.body).getPropertyValue("--factorio-probe").trim())).toBe("active");
    const source=`${root}/apps/factorio/src/lib.rs`, original=await readFile(source,"utf8");
    await writeFile(source,original+'\ncompile_error!("fixture failure");\n');
    const state=async()=>await(await fetch(`${process.env.FACTORIO_FIXTURE_URL}/build-state`)).json();
    await expect.poll(async()=>(await state()).failed,{timeout:60000}).toBe(true);
    await page.reload();await expect(failedCard.getByText("active",{exact:true})).toBeVisible();
    const generations=(await state()).generations;await writeFile(source,original);
    await expect.poll(async()=>(await state()).generations,{timeout:60000}).toBeGreaterThan(generations);
    await expect(failedCard.getByText("active",{exact:true})).toBeVisible();
    const ui=`${root}/apps/factorio/web/pages/workspace.tsx`;await writeFile(ui,(await readFile(ui,"utf8")).replace("Factorio</span>","Updated Factorio development UI.</span>"));
    await expect(page.getByText("Updated Factorio development UI.")).toBeVisible();
  }
  await writeFile(`${failed.worktree}/dirty`,"keep");
  await cli(["abandon","fail"]);expect((await cli(["status"])).sessions.fail.phase).toBe("abandoned");expect(await readFile(`${failed.worktree}/dirty`,"utf8")).toBe("keep");
  expect(errors).toEqual([]);
});
