import { test, expect } from "@playwright/test";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { writeFile, readFile } from "node:fs/promises";
import { resolve } from "node:path";
const exec = promisify(execFile);
const base=process.env.FACTORIO_TEST_URL!, dir=process.env.FACTORIO_FIXTURE_DIR!, root=resolve(import.meta.dirname,"../../../..");
test("fixture-only human acceptance, CLI/UI records, exclusions and restart recovery",async({page,browser})=>{
  await page.setViewportSize({width:390,height:844});
  // HTTP tailnet origins lack randomUUID, including in mobile Safari.
  await page.addInitScript(()=>Reflect.deleteProperty(Object.getPrototypeOf(crypto),"randomUUID"));
  const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
  await page.goto(base);await page.getByRole("link",{name:"Continue with Authy"}).click();
  await page.getByRole("button",{name:"New here? Create account",exact:true}).click();
  await page.getByLabel("Email",{exact:true}).fill(`factorio-${Date.now()}@example.test`);await page.getByLabel("Password",{exact:true}).fill("Factorio fixture password");
  await page.getByRole("button",{name:"Create account",exact:true}).click();await page.getByRole("button",{name:"Allow",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Tickets",exact:true})).toBeVisible();
  await expect(page.getByText("No tickets yet",{exact:true})).toBeVisible();
  const identity=await(await page.request.get(`${base}/api/session`)).json();
  const mutationHeaders={origin:base,"x-snap-csrf":identity.csrf};
  for(let n=0;n<6;n++) expect((await page.request.post(`${base}/api/command`,{headers:mutationHeaders,data:{command:"ticket",ticket:{id:`preceding-${n}`,title:`Earlier ticket ${n}`,description:"Existing work",modules:["a"],status:"draft",notes:"",parent:null,blockers:[]}}})).ok()).toBe(true);
  await page.getByLabel("Your idea",{exact:true}).fill("Improve navigation on my phone");
  await page.getByRole("button",{name:"Work through this",exact:true}).click();
  await expect(page.getByText("Which navigation outcome matters most?",{exact:true})).toBeVisible();
  await expect(page.getByRole("heading",{name:"Tickets",exact:true})).toHaveCount(0);
  for (const height of [844, 420, 844]) {
    await page.setViewportSize({width:390,height});
    await expect.poll(async()=>page.locator(".thread-bottom").evaluate(e=>Math.abs(e.getBoundingClientRect().bottom-(window.visualViewport?.height??innerHeight))<2)).toBe(true);
    await page.locator(".thread-scroll").evaluate(e=>e.scrollTop=0);
    await expect(page.getByRole("button",{name:"Send reply",exact:true})).toBeVisible();
  }
  await page.getByRole("button",{name:"Allow once",exact:true}).click();
  await expect(page.getByLabel("Desired outcome",{exact:true})).toBeVisible();
  await expect(page.getByLabel("Alternate outcome",{exact:true})).toHaveCount(0);
  await expect(page.getByLabel("Unanswered follow-up",{exact:true})).toHaveCount(0);
  await page.getByLabel("Scope custom choices",{exact:true}).fill("");
  const scope=page.getByRole("listbox",{name:"Scope",exact:true});
  await scope.selectOption("known");
  await expect(page.getByLabel("Desired outcome",{exact:true})).toHaveCount(0);
  await expect(page.getByLabel("Alternate outcome",{exact:true})).toBeVisible();
  await scope.selectOption([]);
  await page.getByRole("button",{name:"Send answers",exact:true}).click();
  await expect(scope).toBeVisible();
  expect(await scope.evaluate((e:HTMLSelectElement)=>e.validity.valueMissing)).toBe(true);
  await page.getByLabel("Scope custom choices",{exact:true}).fill("other, other");
  await scope.selectOption("known");
  await scope.selectOption([]);
  await expect(page.getByLabel("Alternate outcome",{exact:true})).toHaveCount(0);
  await page.getByLabel("Desired outcome",{exact:true}).fill("Keep ticket links visible on my phone");
  await page.getByRole("button",{name:"Send answers",exact:true}).click();
  const draft=page.locator("article").filter({has:page.getByRole("heading",{name:"Improve mobile navigation",exact:true})});
  await expect(page.locator(".draft-summary").getByRole("link",{name:"Improve mobile navigation",exact:true})).toBeVisible();
  await page.locator(".draft-summary").getByRole("link",{name:"Improve mobile navigation",exact:true}).click();
  await expect.poll(()=>draft.evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.top<innerHeight;})).toBe(true);
  await page.goBack();
  await page.getByLabel("Reply",{exact:true}).fill("That is the right scope.");
  await page.getByRole("button",{name:"Send reply",exact:true}).click();
  await expect(page.getByText("Your additional context is recorded.")).toBeVisible();
  const conversationURL=page.url();
  const intakeID=new URL(conversationURL).hash.slice(1);
  const stranger=await browser.newContext();
  try {
    const other=await stranger.newPage();await other.goto(base);await other.getByRole("link",{name:"Continue with Authy"}).click();await other.getByRole("button",{name:"New here? Create account",exact:true}).click();await other.getByLabel("Email",{exact:true}).fill(`other-${Date.now()}@example.test`);await other.getByLabel("Password",{exact:true}).fill("Other fixture password");await other.getByRole("button",{name:"Create account",exact:true}).click();await other.getByRole("button",{name:"Allow",exact:true}).click();await expect(other.getByRole("heading",{name:"Tickets",exact:true})).toBeVisible();
    expect((await other.request.get(`${base}/api/intakes/${intakeID}/events`)).ok()).toBe(false);
    const identity=await(await other.request.get(`${base}/api/session`)).json();
    expect((await other.request.post(`${base}/api/intakes/${intakeID}`,{headers:{origin:base,"x-snap-csrf":identity.csrf},data:{action:"interrupt"}})).ok()).toBe(false);
  } finally {await stranger.close();}
  await page.reload();
  await expect(page.getByText("Your additional context is recorded.")).toBeVisible();
  expect(page.url()).toBe(conversationURL);
  await page.getByRole("button",{name:"Mark implementation tickets ready",exact:true}).click();
  await page.screenshot({path:"/tmp/opencode/factorio-thread-ui.png"});
  await page.getByRole("link",{name:"Back to workspace"}).click();
  await expect(page.getByRole("heading",{name:"Tickets",exact:true})).toBeVisible();
  await page.goBack();
  await expect(page.getByLabel("Reply",{exact:true})).toBeVisible();
  await page.goForward();
  await expect(draft.getByText("ready",{exact:true})).toBeVisible();
  await draft.getByRole("link",{name:"Edit",exact:true}).click();
  await expect(page.getByLabel("description",{exact:true})).toHaveValue(/Acceptance:/);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:"/tmp/opencode/factorio-mobile-ui.png",fullPage:true});
  await draft.getByRole("button",{name:"Delete",exact:true}).click();
  await expect(draft).toHaveCount(0);
  await page.getByRole("button",{name:"Create agent token",exact:true}).click();const token=await page.getByLabel("Agent token",{exact:true}).inputValue();expect(token.length).toBeGreaterThan(32);await page.getByRole("button",{name:"Dismiss token"}).click();
  async function cli(args:string[]){const {stdout}=await exec("bun",[`${root}/apps/factorio/cli.ts`,...args],{cwd:root,env:{...process.env,FACTORIO_OPENCODE:`${dir}/bin/opencode`,FACTORIO_ORIGIN:base,FACTORIO_TOKEN:token}});return JSON.parse(stdout);}
  const intake=(Object.values((await cli(["status"])).intakes) as {id:string;conversation:string}[])[0]!;
  expect((await cli(["intake","--resume",intake.id])).resumed).toBe(intake.conversation);
  const credential=JSON.parse(await readFile(`${dir}/resources/intakes/${intake.id}/tool.json`,"utf8"));
  const oldTool=()=>page.request.post(`${base}/api/intake-tool`,{headers:{authorization:`Bearer ${credential.token}`},data:{action:"read"}});
  expect((await oldTool()).ok()).toBe(true);
  await page.getByRole("navigation",{name:"Conversations"}).getByRole("link").click();
  await page.getByText("Drafts and session details",{exact:true}).click();
  page.once("dialog",d=>d.accept());
  await page.getByRole("button",{name:"Delete conversation",exact:true}).click();
  await expect(page.getByLabel("Your idea",{exact:true})).toBeVisible();
  expect((await cli(["status"])).intakes[intake.id]).toBeUndefined();
  expect((await oldTool()).ok()).toBe(false);
  expect((await page.request.post(`${base}/api/intakes`,{headers:mutationHeaders,data:{id:intake.id,description:"Replacement intake"}})).ok()).toBe(true);
  expect((await oldTool()).ok()).toBe(false);
  expect((await page.request.post(`${base}/api/intakes/${intake.id}`,{headers:mutationHeaders,data:{action:"delete"}})).ok()).toBe(true);
  const ticket=(id:string,blockers:string[]=[])=>({id,title:id,description:"Fixture implementation",modules:["a"],status:"ready",notes:"",parent:null,blockers});
  for(const t of [ticket("first"),ticket("dependent",["first"])]){const file=`${dir}/${t.id}.json`;await writeFile(file,JSON.stringify(t));await cli(["ticket",file]);}
  await expect(page.locator("#ticket-first").getByRole("heading",{name:"first",exact:true})).toBeVisible();await expect(page.getByRole("link",{name:"first (ready)"})).toBeVisible();
  await expect(cli(["start","--id","blocked","--tickets","dependent","--modules","a","--","blocked"])).rejects.toThrow();
  const a=(await cli(["start","--id","one","--tickets","first","--modules","a","--","first change"])).session;
  const b=(await cli(["start","--id","two","--modules","b","--","parallel change"])).session;
  expect(a.port).not.toBe(b.port);expect(a.data).not.toBe(b.data);
  await expect(cli(["start","--id","overlap","--modules","a,b","--","overlap"])).rejects.toThrow();
  await expect(cli(["start","--id","whole","--modules","*","--","whole"])).rejects.toThrow();
  const conversations=JSON.parse(await readFile(`${dir}/conversations.json`,"utf8"));expect(conversations[a.conversation].directory).toBe(a.worktree);
  await writeFile(`${a.worktree}/crates/a/file`,"implemented");await exec("git",["add","."],{cwd:a.worktree});await exec("git",["-c","user.name=Fixture","-c","user.email=fixture@localhost","commit","-m","fixture implementation"],{cwd:a.worktree});
  await writeFile(`${dir}/evidence.txt`,"Fixture checks passed; test review found no unresolved findings.");
  const published=await cli(["publish","one","--evidence",`${dir}/evidence.txt`]);const candidate=published.sessions.one.candidate.commit;
  await expect(cli(["accept","one"])).rejects.toThrow(/human approval/);
  const denied=await page.request.post(`${base}/api/approve`,{headers:{authorization:`Bearer ${token}`},data:{id:"one",commit:candidate}});expect(denied.status()).toBe(403);
  // This automated account approves disposable fixture code, never user work.
  page.once("dialog",d=>d.accept());await page.getByRole("button",{name:"Approve candidate as human"}).click();
  await expect.poll(async()=>Boolean((await cli(["status"])).sessions.one.candidate.approval)).toBe(true);
  await cli(["accept","one"]);expect(await readFile(`${dir}/repo/crates/a/file`,"utf8")).toBe("implemented");
  await expect(page.locator("article").filter({has:page.getByRole("heading",{name:"one",exact:true})}).getByText("complete",{exact:true})).toBeVisible();
  await expect(page.getByRole("link",{name:"first (done)"})).toBeVisible();
  const dependent=(await cli(["start","--id","next","--tickets","dependent","--modules","a","--","dependent now ready"])).session;expect(dependent.phase).toBe("active");
  await cli(["abandon","two"]);await expect(cli(["start","--id","fail","--modules","b","--","failed setup"])).rejects.toThrow(/fixture setup failure/);
  await fetch(`${process.env.FACTORIO_FIXTURE_URL}/restart`);await expect(cli(["start","--id","collision","--modules","b","--","collision"])).rejects.toThrow();
  const failed=(await cli(["status"])).sessions.fail;expect(failed.phase).toBe("starting");await writeFile(`${failed.data}/permit`,"retry fixture hook");
  await cli(["recover","fail"]);expect((await cli(["status"])).sessions.fail.phase).toBe("active");
  await page.reload();const failedCard=page.locator("article").filter({has:page.getByRole("heading",{name:"fail",exact:true})});await expect(failedCard.getByText("active",{exact:true})).toBeVisible();
  if(process.env.FACTORIO_TEST_DEV){
    const css=`${root}/apps/factorio/web/style.css`;await writeFile(css,await readFile(css,"utf8")+"\nbody { --factorio-probe: active; }\n");
    await expect.poll(()=>page.evaluate(()=>getComputedStyle(document.body).getPropertyValue("--factorio-probe").trim())).toBe("active");
    const source=`${root}/apps/factorio/src/lib.rs`, original=await readFile(source,"utf8");
    await writeFile(source,original+'\ncompile_error!("fixture failure");\n');
    const state=async()=>await(await fetch(`${process.env.FACTORIO_FIXTURE_URL}/build-state`)).json();
    await expect.poll(async()=>(await state()).failed,{timeout:60000}).toBe(true);
    await page.reload();await expect(failedCard.getByText("active",{exact:true})).toBeVisible();
    const generations=(await state()).generations;await writeFile(source,original);
    await expect.poll(async()=>(await state()).generations,{timeout:60000}).toBeGreaterThan(generations);
    await expect(failedCard.getByText("active",{exact:true})).toBeVisible();
    const ui=`${root}/apps/factorio/web/main.tsx`;await writeFile(ui,(await readFile(ui,"utf8")).replace("Track work from idea to review.","Updated Factorio development UI."));
    await expect(page.getByText("Updated Factorio development UI.")).toBeVisible();
  }
  await writeFile(`${failed.worktree}/dirty`,"keep");
  await cli(["abandon","fail"]);expect((await cli(["status"])).sessions.fail.phase).toBe("abandoned");expect(await readFile(`${failed.worktree}/dirty`,"utf8")).toBe("keep");
  expect(errors).toEqual([]);
});
