[package]
name = "authy"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
snap-store.workspace = true
snap-identity.workspace = true
snap-access.workspace = true
snap-document.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true

[dev-dependencies]
snap-sqlite = { path = "../../platforms/sqlite" }
toml = "0.9"

[package.metadata.snap]
role = "application"
