import { test, expect } from "bun:test";
import { Socket } from "../support/socket";
import { createPublicKey, verify, createHash } from "node:crypto";
import { oidcServer, clientOrigin, clientSecret } from "../support/oidc";
import { deadline } from "../../../../tests/adapters/server";
import { hosts } from "../support/platform";

for (const host of hosts) {
test(`${host} OIDC: profile, consent, PKCE, signed claims, rotation, replay and restart`, async () => {
  const server = await oidcServer(host);
  const sockets: WebSocket[] = [];
  const base = server.baseUrl;
  const verifier = "dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk";
  const challenge = "E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM";
  const basic = `Basic ${Buffer.from(`chatty:${clientSecret}`).toString("base64")}`;
  const request = (path: string, init: RequestInit = {}) => fetch(`${base}${path}`, { redirect: "manual", ...init });
  const form = (path: string, data: Record<string, string>, headers: Record<string, string> = {}) => request(path, { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded", ...headers }, body: new URLSearchParams(data) });
  const params = (extra: Record<string, string> = {}) => new URLSearchParams({ client_id: "chatty", redirect_uri: `${clientOrigin}/auth/callback`, response_type: "code", scope: "openid profile email", state: "test-state", nonce: "test-nonce", code_challenge: challenge, code_challenge_method: "S256", ...extra });
  const signIn = async (register: boolean) => {
    const r = await request(register ? "/account/create" : "/identity/password/acquire", { method: "POST", headers: { "x-snap-build": "healthy-smoke", "content-type": "application/json", origin: base }, body: JSON.stringify({ email: "oidc@example.test", password: "password for oidc", kind: "user" }) });
    expect((await r.json()).payload.ok).toBe(true);
    return r.headers.get("set-cookie")!.split(";")[0];
  };
  let cookie: string;
  const authorize = async () => {
    const r = await request(`/oauth/authorize?${params()}`, { headers: { cookie } });
    expect(r.status).toBe(200);
    expect(r.headers.get("content-security-policy")).toContain("frame-ancestors 'none'");
    const handle = (await r.text()).match(/name=request value="([^"]+)"/)![1];
    const approved = await form("/oauth/authorize", { request: handle, decision: "allow" }, { cookie, origin: base });
    expect(approved.status).toBe(303);
    const redirect = new URL(approved.headers.get("location")!);
    expect(redirect.origin).toBe(clientOrigin); expect(redirect.searchParams.get("state")).toBe("test-state"); expect(redirect.searchParams.get("iss")).toBe(base);
    expect((await form("/oauth/authorize", { request: handle, decision: "allow" }, { cookie, origin: base })).status).toBe(400);
    return redirect.searchParams.get("code")!;
  };
  const exchange = (code: string, other: Record<string,string> = {}) => form("/oauth/token", { grant_type: "authorization_code", code, redirect_uri: `${clientOrigin}/auth/callback`, code_verifier: verifier, ...other }, { authorization: basic });
  const info = (token: string) => request("/oauth/userinfo", { headers: { authorization: `Bearer ${token}` } });
  try {
    const discovery = await (await request("/.well-known/openid-configuration")).json();
    expect(discovery.issuer).toBe(base); expect(discovery.code_challenge_methods_supported).toEqual(["S256"]);
    expect(discovery.token_endpoint_auth_methods_supported).toContain("client_secret_basic");
    const jwks = await (await request("/oauth/jwks")).json();
    expect(jwks.keys).toHaveLength(1); expect(jwks.keys[0].d).toBeUndefined();
    expect((await request(`/oauth/authorize?${params({ redirect_uri: "https://attacker.example/" })}`)).headers.get("location")).toBeNull();
    const silent = await request(`/oauth/authorize?${params({ prompt: "none" })}`);
    expect(new URL(silent.headers.get("location")!).searchParams.get("error")).toBe("login_required");
    cookie = await signIn(true);
    let profile = await (await request("/api/account", { headers: { cookie } })).json();
    expect(profile.name).toBe("oidc"); expect(profile.email_verified).toBe(false);
    const profileWrite = () => request("/api/account", { method: "POST", headers: { cookie, origin: base, "content-type": "application/json" }, body: JSON.stringify({ name: "OIDC Person", bio: "A persistent profile", revision: profile.revision }) });
    expect((await profileWrite()).status).toBe(200); expect((await profileWrite()).status).toBe(409);
    profile = await (await request("/api/account", { headers: { cookie } })).json();
    const code = await authorize();
    expect((await exchange(code, { code_verifier: "x".repeat(43) })).status).toBe(400);
    expect((await form("/oauth/token", { client_id: "chatty", grant_type: "authorization_code", code, code_verifier: verifier, redirect_uri: `${clientOrigin}/auth/callback` })).status).toBe(401);
    const response = await exchange(code); expect(response.status).toBe(200); expect(response.headers.get("cache-control")).toBe("no-store");
    const tokens = await response.json();
    const parts = tokens.id_token.split(".");
    expect(verify("RSA-SHA256", Buffer.from(parts.slice(0, 2).join(".")), createPublicKey({ key: jwks.keys[0], format: "jwk" }), Buffer.from(parts[2], "base64url"))).toBe(true);
    const claims = JSON.parse(Buffer.from(parts[1], "base64url").toString());
    expect(claims).toMatchObject({ iss: base, aud: "chatty", sub: profile.id, name: "OIDC Person", email: "oidc@example.test", email_verified: false, nonce: "test-nonce" });
    expect(claims.at_hash).toBe(createHash("sha256").update(tokens.access_token).digest().subarray(0, 16).toString("base64url"));
    expect(claims.exp - claims.iat).toBe(600);
    expect((await info(tokens.access_token)).status).toBe(200);
    await server.restart();
    expect(await (await request("/oauth/jwks")).json()).toEqual(jwks);
    expect((await info(tokens.access_token)).status).toBe(200);
    const refresh = (token: string) => form("/oauth/token", { grant_type: "refresh_token", refresh_token: token }, { authorization: basic });
    const rotatedResponse = await refresh(tokens.refresh_token); expect(rotatedResponse.status).toBe(200);
    const rotated = await rotatedResponse.json(); expect(rotated.refresh_token).not.toBe(tokens.refresh_token);
    expect((await refresh(tokens.refresh_token)).status).toBe(400);
    expect((await info(rotated.access_token)).status).toBe(401);
    expect((await refresh(rotated.refresh_token)).status).toBe(400);
    const replayCode = await authorize(); const replayTokens = await (await exchange(replayCode)).json();
    expect((await exchange(replayCode)).status).toBe(400); expect((await info(replayTokens.access_token)).status).toBe(401);
    const active = await (await exchange(await authorize())).json();
    const revoke = await form("/oauth/revoke", { token: active.refresh_token }, { authorization: basic });
    expect(revoke.status).toBe(200); expect((await info(active.access_token)).status).toBe(401);
    expect((await request("/oauth/token", { method: "POST", headers: { "content-type": "application/json" }, body: "{}" })).status).toBe(415);
    const stale = await request(`/oauth/authorize?${params({ max_age: "0" })}`, { headers: { cookie } });
    expect(stale.status).toBe(303);
    const resume = new URL(stale.headers.get("location")!, base).searchParams.get("return_to")!;
    expect((await request(resume, { headers: { cookie } })).status).toBe(400);
    cookie = await signIn(false);
    expect((await request(resume, { headers: { cookie } })).status).toBe(200);
    const concurrentCode = await authorize();
    const redemptions = await Promise.all([exchange(concurrentCode), exchange(concurrentCode)]);
    expect(redemptions.map(r => r.status).sort()).toEqual([200, 400]);
    const logoutTokens = await (await exchange(await authorize())).json();
    const idle = new Socket(`${base.replace("http:", "ws:")}/_transport/ws?build=healthy-smoke&clientId=oidc-logout`, { headers: { origin: base, cookie } });
    sockets.push(idle);
    await deadline(new Promise<void>((done, fail) => {
      idle.addEventListener("message", event => { if (JSON.parse(String(event.data)).key === "transport.epoch") done(); });
      idle.addEventListener("error", () => fail(new Error("Idle socket failed")));
    }), 5000);
    const closed = new Promise<CloseEvent>(done => idle.addEventListener("close", done, { once: true }));
    const initiate = await form("/oauth/logout", { client_id: "chatty", post_logout_redirect_uri: `${clientOrigin}/auth/logged-out`, id_token_hint: logoutTokens.id_token, state: "logout-state" }, { cookie });
    expect(initiate.status).toBe(200);
    const logoutHandle = (await initiate.text()).match(/name=request value="([^"]+)"/)![1];
    expect((await form("/oauth/logout", { request: logoutHandle }, { cookie, origin: "https://attacker.example" })).status).toBe(403);
    const loggedOut = await form("/oauth/logout", { request: logoutHandle }, { cookie, origin: base });
    expect(loggedOut.status).toBe(303); expect(loggedOut.headers.get("set-cookie")).toContain("Max-Age=0");
    expect((await deadline(closed, 5000)).code).toBe(4001);
    expect(new URL(loggedOut.headers.get("location")!).searchParams.get("state")).toBe("logout-state");
    expect((await info(logoutTokens.access_token)).status).toBe(401);
    expect((await request("/api/account", { headers: { cookie } })).status).toBe(401);
    cookie = await signIn(false);
    expect((await request("/oauth/logout", { headers: { cookie } })).status).toBe(200);
  } finally { for (const socket of sockets) socket.close(); await server.close(); }
}, 120_000);
}
