import { test, expect } from "bun:test";
import { createPublicKey, verify, createHash } from "node:crypto";
import { host } from "../support/upgraded-host";

test("real issuer: consent, PKCE, signed claims, restart, refresh replay, revocation and logout", async () => {
  const server = await host();
  const base = server.base;
  const redirect = "http://127.0.0.1:3850/auth/callback";
  const verifier = "dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk";
  const challenge = "E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM";
  const basic = `Basic ${Buffer.from(`chatty:${server.clientSecret}`).toString("base64")}`;
  const request = (path: string, init: RequestInit = {}) => fetch(`${base}${path}`, { ...init, redirect: "manual" });
  const form = (path: string, body: Record<string,string>, headers: Record<string,string> = {}) => request(path, { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded", ...headers }, body: new URLSearchParams(body) });
  const params = (extra: Record<string,string> = {}) => new URLSearchParams({ client_id: "chatty", redirect_uri: redirect, response_type: "code", scope: "openid profile email", state: "fixture-state", nonce: "fixture-nonce", code_challenge: challenge, code_challenge_method: "S256", ...extra });
  const handle = (html: string) => { const match = /name="?request"?\s+value="([^"]+)"/.exec(html); expect(match).not.toBeNull(); return match![1]; };
  let cookie = "";
  async function login(signup = false) {
    const response = await request(signup ? "/api/signup" : "/api/login", { method: "POST", headers: { origin: base, "content-type":"application/json" }, body: JSON.stringify({email:"oidc@example.test",password:"OIDC fixture password"}) });
    expect(response.status).toBe(200);
    cookie = response.headers.get("set-cookie")!.split(";")[0];
    return (await response.json()).account;
  }
  async function authorize() {
    const response = await request(`/oauth/authorize?${params()}`, { headers:{cookie} });
    expect(response.status).toBe(200);
    expect(response.headers.get("content-security-policy")).toContain("frame-ancestors 'none'");
    const ticket = handle(await response.text());
    const approved = await form("/oauth/authorize",{request:ticket,decision:"allow"},{cookie,origin:base});
    expect(approved.status).toBe(303);
    const location = new URL(approved.headers.get("location")!);
    expect(location.origin).toBe("http://127.0.0.1:3850");
    expect(location.searchParams.get("state")).toBe("fixture-state");
    expect(location.searchParams.get("iss")).toBe(base);
    expect((await form("/oauth/authorize",{request:ticket,decision:"allow"},{cookie,origin:base})).status).toBe(400);
    return location.searchParams.get("code")!;
  }
  const exchange = (code:string, code_verifier=verifier) => form("/oauth/token",{grant_type:"authorization_code",code,redirect_uri:redirect,code_verifier},{authorization:basic});
  const refresh = (refresh_token:string) => form("/oauth/token",{grant_type:"refresh_token",refresh_token},{authorization:basic});
  const info = (token:string) => request("/oauth/userinfo",{headers:{authorization:`Bearer ${token}`}});
  try {
    const discovery = await (await request("/.well-known/openid-configuration")).json();
    expect(discovery.issuer).toBe(base);
    expect(discovery.code_challenge_methods_supported).toEqual(["S256"]);
    const jwks = await (await request("/oauth/jwks")).json();
    expect(jwks.keys).toHaveLength(1); expect(jwks.keys[0].d).toBeUndefined();
    const badRedirect = await request(`/oauth/authorize?${params({redirect_uri:"https://attacker.invalid/"})}`);
    expect(badRedirect.status).toBe(400); expect(badRedirect.headers.get("location")).toBeNull();
    const silent = await request(`/oauth/authorize?${params({prompt:"none"})}`);
    expect(new URL(silent.headers.get("location")!).searchParams.get("error")).toBe("login_required");
    const account = await login(true);
    const tampered = cookie.slice(0,-1) + (cookie.endsWith("A") ? "B" : "A");
    expect((await (await request("/api/session",{headers:{cookie:tampered}})).json()).account).toBeNull();
    expect((await (await request("/api/session",{headers:{cookie:`${cookie}; ${cookie}`}})).json()).account).toBeNull();
    const code = await authorize();
    expect((await exchange(code,"x".repeat(43))).status).toBe(400);
    expect((await form("/oauth/token",{client_id:"chatty",grant_type:"authorization_code",code,redirect_uri:redirect,code_verifier:verifier})).status).toBe(401);
    const response = await exchange(code); expect(response.status).toBe(200);
    expect(response.headers.get("cache-control")).toBe("no-store");
    const tokens = await response.json();
    const parts = tokens.id_token.split(".");
    expect(verify("RSA-SHA256",Buffer.from(parts.slice(0,2).join(".")),createPublicKey({key:jwks.keys[0],format:"jwk"}),Buffer.from(parts[2],"base64url"))).toBe(true);
    const claims = JSON.parse(Buffer.from(parts[1],"base64url").toString());
    expect(claims).toMatchObject({iss:base,aud:"chatty",sub:account.identity,nonce:"fixture-nonce",email:"oidc@example.test",email_verified:false});
    expect(claims.at_hash).toBe(createHash("sha256").update(tokens.access_token).digest().subarray(0,16).toString("base64url"));
    expect(claims.exp-claims.iat).toBe(600);
    expect((await info(tokens.access_token)).status).toBe(200);
    await server.restart();
    expect(await (await request("/oauth/jwks")).json()).toEqual(jwks);
    expect((await info(tokens.access_token)).status).toBe(200);
    expect((await (await request("/api/session",{headers:{cookie}})).json()).account.identity).toBe(account.identity);
    const rotatedResponse = await refresh(tokens.refresh_token); expect(rotatedResponse.status).toBe(200);
    const rotated = await rotatedResponse.json(); expect(rotated.refresh_token).not.toBe(tokens.refresh_token);
    expect((await refresh(tokens.refresh_token)).status).toBe(400);
    expect((await info(rotated.access_token)).status).toBe(401);
    expect((await refresh(rotated.refresh_token)).status).toBe(400);
    const replayCode = await authorize(); const replay = await (await exchange(replayCode)).json();
    expect((await exchange(replayCode)).status).toBe(400);
    expect((await info(replay.access_token)).status).toBe(401);
    const revoked = await (await exchange(await authorize())).json();
    expect((await form("/oauth/revoke",{token:revoked.refresh_token},{authorization:basic})).status).toBe(200);
    expect((await info(revoked.access_token)).status).toBe(401);
    const forced = await request(`/oauth/authorize?${params({max_age:"0"})}`,{headers:{cookie}});
    expect(forced.status).toBe(303);
    const destination = new URL(forced.headers.get("location")!,base);
    const resume = destination.searchParams.get("continue")!;
    expect(resume).toStartWith("/oauth/resume?");
    expect((await request(resume,{headers:{cookie}})).status).toBe(400);
    await login();
    expect((await request(resume,{headers:{cookie}})).status).toBe(200);
    const active = await (await exchange(await authorize())).json();
    const logout = await form("/oauth/logout",{client_id:"chatty",post_logout_redirect_uri:"http://127.0.0.1:3850/auth/logged-out",id_token_hint:active.id_token,state:"logout-state"},{cookie});
    expect(logout.status).toBe(200); const logoutTicket=handle(await logout.text());
    expect((await form("/oauth/logout",{request:logoutTicket},{cookie,origin:"https://attacker.invalid"})).status).toBe(403);
    const ended=await form("/oauth/logout",{request:logoutTicket},{cookie,origin:base});
    expect(ended.status).toBe(303); expect(ended.headers.get("set-cookie")).toContain("Max-Age=0");
    expect(new URL(ended.headers.get("location")!).searchParams.get("state")).toBe("logout-state");
    expect((await info(active.access_token)).status).toBe(401);
  } finally { await server.close(); }
},120000);
