id = "0005_factorio_cli"

[[changes]]
action = "create_table"
[changes.table]
name = "factorio.cli"
columns = [{ name = "id", kind = "text" }, { name = "session", kind = "text" }, { name = "expires", kind = "integer" }]
primary = ["id"]

[[changes]]
action = "create_table"
[changes.table]
name = "factorio.cli_login"
columns = [{ name = "id", kind = "text" }, { name = "proof", kind = "text" }, { name = "session", kind = "text" }, { name = "expires", kind = "integer" }]
primary = ["id"]
