version = 1
application = "chatty"

[build]

[check]
rust = ["Cargo.toml", "native/Cargo.toml", "wasm/Cargo.toml"]
typescript = ["web/tsconfig.json"]

[test.memory]
commands = [["cargo", "test", "-p", "chatty"]]

[test.browser]
commands = [["../../bin/browser-tests", "chatty"]]

[test.native]
commands = [["cargo", "test", "-p", "chatty-native", "--", "--ignored"], ["cargo", "test", "-p", "snap-oauth-local", "--test", "crypto", "--", "--ignored"]]
